# Generated by Django 3.2.13 on 2025-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16)),
                ('c_gril_num', models.IntegerField(default=5)),
                ('c_boy_num', models.IntegerField(default=3)),
            ],
        ),
    ]
