# Generated by Django 3.2.13 on 2024-10-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_hobby',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
